version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: howsy/code-challenge
    command: ['./vendor/bin/phpunit --testdox tests']
    tty: true
    volumes:
       - './src:/usr/src/howsy'